
"""Add shared_documents table

Revision ID: 9a5067c8b415
Revises: 67e617128412
Create Date: 2026-05-14 19:03:01.632800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a5067c8b415'
down_revision: Union[str, None] = '67e617128412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_name', sa.String(length=300), nullable=False),
    sa.Column('filesize', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('shared_documents_uploaded_by_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('shared_documents_pkey')),
    sa.UniqueConstraint('storage_name', name=op.f('shared_documents_storage_name_key'))
    )
    op.create_index(op.f('shared_documents_uploaded_by_id_idx'), 'shared_documents', ['uploaded_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('shared_documents_uploaded_by_id_idx'), table_name='shared_documents')
    op.drop_table('shared_documents')
    # ### end Alembic commands ###
